apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: amd-gpu-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: amd-gpu-dp-ds
  template:
    metadata:
      labels:
        name: amd-gpu-dp-ds
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - name: amd-gpu-dp-cntr
          image: docker.io/rocm/k8s-device-plugin:{{ .Values.DevicePluginVersion }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          volumeMounts:
            - name: dp
              mountPath: /var/lib/kubelet/device-plugins
            - name: sys
              mountPath: /sys
          resources:
            {}
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys
