{
 "title": "ROCm Data Center tool V1.0",
 "description": "Dashboard to monitor AMD GPUs using RDC",
 "tags": [ "IB" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(gpu_temp, instance)"
   },
   { "name": "gpu_index", "query": "label_values(gpu_index)" }
  ]
 },
 "panels": [
  {
   "title": "Average GPU Package Power (Watt)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "power_usage{instance=~\"$node.*\",gpu_index=~\"${gpu_index}\"}",
     "legendFormat": "{{short_instance}}:gpu{{gpu_index}}"
    }
   ]
  },
  {
   "title": "GPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gpu_util{instance=~\"$node.*\",gpu_index=~\"${gpu_index}\"}",
     "legendFormat": "{{short_instance}}:gpu{{gpu_index}}"
    }
   ]
  },
  {
   "title": "GPU Clock Speed (MHz)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpu_clock{instance=~\"$node.*\",gpu_index=~\"${gpu_index}\"}",
     "legendFormat": "{{short_instance}}:gpu{{gpu_index}}"
    }
   ]
  },
  {
   "title": "GPU Temperature (Celsius)",
   "type": "graph",
   "description": "The GPU temperature in degree",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpu_temp{instance=~\"$node.*\",gpu_index=~\"${gpu_index}\"}",
     "legendFormat": "gpu{{gpu_index}}"
    }
   ]
  },
  {
   "title": "GPU Memory Allocation (GB)",
   "type": "graph",
   "description": "the amount of total available and allocated VRAM",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=~\"${gpu_index}\"} / 1024",
     "legendFormat": "{{short_instance}}:gpu{{gpu_index}}  - Allocated"
    }
   ]
  },
  {
   "title": "GPU Memory Activity Level (%)",
   "type": "graph",
   "description": "indicate how busy the respective mem blocks are",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gpu_memory_usage{instance=~\"$node.*\",gpu_index=~\"${gpu_index}\"}*100/gpu_memory_total{instance=~\"$node.*\",gpu_index=~\"${gpu_index}\"}",
     "legendFormat": "{{short_instance}}:gpu{{gpu_index}}"
    }
   ]
  }
 ]
}