# Reference to ROCm-terminal
# Source: https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/rocm-terminal
#
# Following pacakages in ROCm-terminal are "NOT" installed here
# sudo, libelf1, libnuma-dev, build-essential, git, cmake-curses-gui, kmod, file, rocm-dev

FROM ubuntu:20.04
USER root

ARG ROCM_VERSION=5.5
ARG AMDGPU_VERSION=5.5

## requriements inatallation 
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates curl gnupg && \
    curl -sL http://repo.radeon.com/rocm/rocm.gpg.key | apt-key add - && \
    sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/$ROCM_VERSION/ focal main > /etc/apt/sources.list.d/rocm.list' && \
    sh -c 'echo deb [arch=amd64] https://repo.radeon.com/amdgpu/$AMDGPU_VERSION/ubuntu focal main > /etc/apt/sources.list.d/amdgpu.list' && \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends vim-nox python3 python3-pip && \
    apt-get install -y libcap-dev supervisor && \
    apt-get install -y rdc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install prometheus_client && \
    ldconfig /opt/rocm/rdc/lib

## copy needed files
COPY ../python_binding /rdc/python_binding
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

## set environments variable
ENV PATH "${PATH}:/opt/rocm/bin"

## start service
CMD ["/usr/bin/supervisord"]
